name: On Pull Request Quality Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm i

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules

  unit_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules
      - name: Unit Tests
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules
      - name: Lint
        run: npm run lint

  deploy_amplify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Install CLI
        run: npm install -g @aws-amplify/cli
      - name: Deploy
        run: sh deploy_prod.sh
